# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master  # Only build for changes in master branch (and pull requests)

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'unmockwebsite2:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
    yarn
  displayName: 'Initialize yarn'

- script: |
    docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  displayName: 'build container'

- script: |
    docker login -u $(dockerId) -p $DOCKER_PASSWORD $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'push to container registry'
  env:
    DOCKER_PASSWORD: $(dockerPassword)
